/**
 * shiny-sorter
 * Endpoint definitions for the shiny-sorter file sorting project
 *
 * OpenAPI spec version: alpha-v0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QuestionTagOptions } from './questionTagOptions';


export interface Question { 
    questionID?: number;
    orderingID?: number;
    questionText?: string;
    tagOptions?: Array<QuestionTagOptions>;
    /**
     * Whether this functions as an \"and\" (true, only one option selected) or an \"or\" question false, default, can select multiple)
     */
    mutuallyExclusive?: boolean;
}
