create table "public"."files" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "filename" text not null default ''::text,
    "md5sum" text not null default ''::text,
    "hasBeenTagged" boolean not null default false
);


create table "public"."filetags" (
    "id" bigint generated by default as identity not null,
    "fileid" bigint not null,
    "tagid" smallint
);


create table "public"."questionoptions" (
    "id" bigint generated by default as identity not null,
    "tagid" smallint,
    "questionid" bigint,
    "optiontext" text
);


create table "public"."questions" (
    "id" bigint generated by default as identity not null,
    "orderingID" smallint not null default '0'::smallint,
    "questionText" text not null default ''::text
);


create table "public"."tags" (
    "id" smallint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" text not null default ''::text,
    "description" text not null default ''::text
);



